FAQ = [
    ("hola", "¡Hola! Bienvenido a SoftDev, ¿en qué puedo ayudarte?"),
    ("buenas", "¡Buenas! Gracias por contactar con SoftDev, ¿qué necesitas?"),
    ("que hace softdev", "SoftDev es una empresa especializada en desarrollo de software, consultoría tecnológica y soluciones IT personalizadas."),
    ("quienes son ustedes", "Somos SoftDev, un equipo de profesionales que crea soluciones digitales a medida para empresas y startups."),
    ("donde estan ubicados", "Nuestra oficina principal está en Avenida Inventada 36, Rota, Cádiz."),
    ("direccion", "Estamos en Rota, Cádiz. Si quieres, puedo enviarte la ubicación en el mapa."),
    ("horario", "Atendemos de lunes a viernes de 9:00 a 18:00 (CET)."),
    ("a que hora abren", "Abrimos a las 9:00 de la mañana y cerramos a las 18:00."),
    ("metodo de trabajo", "Aplicamos metodologías ágiles como Scrum y Kanban, priorizando entregas rápidas y feedback continuo."),
    ("como trabajan", "Trabajamos con procesos ágiles y comunicación constante con el cliente para garantizar buenos resultados."),
    ("que servicios ofrecen", "Ofrecemos desarrollo de software, integración de sistemas, mantenimiento técnico y consultoría IT."),
    ("servicios disponibles", "Nuestros servicios incluyen desarrollo web, móvil, migración a la nube y automatización de procesos."),
    ("precio", "Nuestras tarifas son transparentes y se ajustan al alcance del proyecto. Podemos darte un presupuesto sin compromiso."),
    ("cuanto cuesta", "Depende del tipo de proyecto, pero todos nuestros presupuestos son personalizados y claros."),
    ("presupuesto", "Puedes solicitar un presupuesto gratuito desde nuestro sitio web o agendando una consulta. Respondemos en menos de 48 horas."),
    ("tecnologias", "Usamos JavaScript, React, Python, Node.js, .NET y tecnologías cloud como AWS y Azure."),
    ("stack tecnologico", "Trabajamos con un stack moderno: TypeScript, Docker, microservicios y bases de datos SQL/NoSQL."),
    ("empleo", "Estamos en búsqueda de desarrolladores y diseñadores para unirse a nuestro equipo. ¿Te gustaría postular?"),
    ("trabajar en softdev", "Ofrecemos un ambiente colaborativo con proyectos desafiantes y oportunidades de crecimiento."),
    ("clientes", "Hemos trabajado con startups, pymes y grandes empresas en sectores como fintech, salud y e-commerce."),
    ("experiencia", "Contamos con más de 10 años de experiencia y más de 200 proyectos exitosos."),
    ("seguridad", "Implementamos protocolos avanzados y cumplimos con normativas como GDPR e ISO 27001."),
    ("nube", "Desplegamos soluciones escalables en AWS, Azure y Google Cloud."),
    ("proyectos", "Realizamos aplicaciones móviles, sistemas empresariales y plataformas digitales a medida."),
    ("formacion", "Damos talleres y mentorías técnicas sobre programación, metodologías ágiles y herramientas modernas."),
    ("capacitacion", "Ofrecemos programas de formación técnica adaptados a equipos de desarrollo y empresas."),
    ("colaboracion", "Nos gusta trabajar mano a mano con nuestros clientes para lograr resultados efectivos."),
    ("soporte", "Nuestro equipo de soporte está disponible de lunes a viernes, con atención urgente fuera de horario laboral."),
    ("contacto", "Puedes escribirnos a soporte@softdev.com o llamarnos al 955 123 456."),
    ("como comunicarse", "Puedes contactarnos por correo, teléfono o desde el formulario web."),
    ("adios", "¡Hasta luego! Gracias por visitar SoftDev."),
    ("gracias", "¡Gracias por confiar en SoftDev! Estamos para ayudarte."),
    ("problema tecnico", "Si tienes algún fallo o incidencia, abre un ticket de soporte y te ayudaremos cuanto antes."),
    ("consultoria", "Ofrecemos asesoramiento tecnológico para optimizar procesos y sistemas empresariales."),
    ("quiero colaborar", "Nos encanta crear alianzas estratégicas. Cuéntanos tu idea y vemos cómo trabajar juntos."),
    ("formulario", "Puedes rellenar el formulario web para que nuestro equipo se ponga en contacto contigo."),
]

